=== pontos-cc/open-data/schemas/exchange-rate.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ExchangeRate",
  "definitions": {
    "ExchangeRate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "result": {
          "type": "string"
        },
        "documentation": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ]
        },
        "terms_of_use": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ]
        },
        "time_last_update_unix": {
          "type": "integer"
        },
        "time_last_update_utc": {
          "type": "string"
        },
        "time_next_update_unix": {
          "type": "integer"
        },
        "time_next_update_utc": {
          "type": "string"
        },
        "base_code": {
          "type": "string"
        },
        "conversion_rates": {
          "type": "object",
          "additionalProperties": {
            "type": "number"
          }
        }
      },
      "required": [
        "base_code",
        "conversion_rates",
        "documentation",
        "result",
        "terms_of_use",
        "time_last_update_unix",
        "time_last_update_utc",
        "time_next_update_unix",
        "time_next_update_utc"
      ],
      "title": "ExchangeRate",
      "$schema": "http://json-schema.org/draft-07/schema#"
    }
  }
}

=== pontos-cc/open-data/data/exchange-rate/BRL.json
{
  "result": "success",
  "documentation": "https://www.exchangerate-api.com/docs",
  "terms_of_use": "https://www.exchangerate-api.com/terms",
  "time_last_update_unix": 1752451201,
  "time_last_update_utc": "Mon, 14 Jul 2025 00:00:01 +0000",
  "time_next_update_unix": 1752537601,
  "time_next_update_utc": "Tue, 15 Jul 2025 00:00:01 +0000",
  "base_code": "BRL",
  "conversion_rates": {
    "BRL": 1,
    "AED": 0.661,
    "AFN": 12.4465,
    "ALL": 15.0467,
    "AMD": 69.0976,
    "ANG": 0.3222,
    "AOA": 165.7509,
    "ARS": 227.0516,
    "AUD": 0.2736,
    "AWG": 0.3222,
    "AZN": 0.3058,
    "BAM": 0.301,
    "BBD": 0.3599,
    "BDT": 21.8735,
    "BGN": 0.301,
    "BHD": 0.06767,
    "BIF": 537.9706,
    "BMD": 0.18,
    "BND": 0.2304,
    "BOB": 1.2461,
    "BSD": 0.18,
    "BTN": 15.4409,
    "BWP": 2.4034,
    "BYN": 0.5427,
    "BZD": 0.3599,
    "CAD": 0.2463,
    "CDF": 522.6,
    "CHF": 0.1433,
    "CLP": 171.841,
    "CNY": 1.2898,
    "COP": 721.7845,
    "CRC": 90.6623,
    "CUP": 4.3194,
    "CVE": 16.9721,
    "CZK": 3.7958,
    "DJF": 31.9852,
    "DKK": 1.1485,
    "DOP": 10.8348,
    "DZD": 23.3217,
    "EGP": 8.9033,
    "ERN": 2.6996,
    "ETB": 25.0676,
    "EUR": 0.1539,
    "FJD": 0.4029,
    "FKP": 0.1332,
    "FOK": 1.1485,
    "GBP": 0.1332,
    "GEL": 0.4882,
    "GGP": 0.1332,
    "GHS": 1.8831,
    "GIP": 0.1332,
    "GMD": 13.0737,
    "GNF": 1565.3687,
    "GTQ": 1.3807,
    "GYD": 37.61,
    "HKD": 1.4128,
    "HNL": 4.7015,
    "HRK": 1.1597,
    "HTG": 23.6013,
    "HUF": 61.4863,
    "IDR": 2924.2145,
    "ILS": 0.599,
    "IMP": 0.1332,
    "INR": 15.441,
    "IQD": 235.5064,
    "IRR": 7801.0903,
    "ISK": 21.9004,
    "JEP": 0.1332,
    "JMD": 28.7878,
    "JOD": 0.1276,
    "JPY": 26.5212,
    "KES": 23.209,
    "KGS": 15.7234,
    "KHR": 722.0132,
    "KID": 0.2732,
    "KMF": 75.7242,
    "KRW": 248.19,
    "KWD": 0.05491,
    "KYD": 0.15,
    "KZT": 94.006,
    "LAK": 3915.4295,
    "LBP": 16107.6761,
    "LKR": 54.0027,
    "LRD": 36.0381,
    "LSL": 3.2231,
    "LYD": 0.9689,
    "MAD": 1.6182,
    "MDL": 3.0381,
    "MGA": 795.2609,
    "MKD": 9.4946,
    "MMK": 378.2529,
    "MNT": 648.4394,
    "MOP": 1.4552,
    "MRU": 7.1758,
    "MUR": 8.165,
    "MVR": 2.7785,
    "MWK": 311.9976,
    "MXN": 3.357,
    "MYR": 0.7659,
    "MZN": 11.4362,
    "NAD": 3.2231,
    "NGN": 274.2686,
    "NIO": 6.6142,
    "NOK": 1.8219,
    "NPR": 24.7055,
    "NZD": 0.2993,
    "OMR": 0.0692,
    "PAB": 0.18,
    "PEN": 0.6387,
    "PGK": 0.7424,
    "PHP": 10.1765,
    "PKR": 51.193,
    "PLN": 0.6564,
    "PYG": 1407.8637,
    "QAR": 0.6551,
    "RON": 0.782,
    "RSD": 18.0214,
    "RUB": 14.0197,
    "RWF": 259.0795,
    "SAR": 0.6749,
    "SBD": 1.4793,
    "SCR": 2.6008,
    "SDG": 80.3411,
    "SEK": 1.7198,
    "SGD": 0.2304,
    "SHP": 0.1332,
    "SLE": 4.041,
    "SLL": 4040.9814,
    "SOS": 102.7584,
    "SRD": 6.7066,
    "SSP": 844.7169,
    "STN": 3.7711,
    "SYP": 2288.0836,
    "SZL": 3.2231,
    "THB": 5.8338,
    "TJS": 1.8806,
    "TMT": 0.6327,
    "TND": 0.5206,
    "TOP": 0.43,
    "TRY": 7.2277,
    "TTD": 1.2106,
    "TVD": 0.2732,
    "TWD": 5.2517,
    "TZS": 468.6687,
    "UAH": 7.5256,
    "UGX": 644.9393,
    "USD": 0.18,
    "UYU": 7.3022,
    "UZS": 2285.4778,
    "VES": 20.7562,
    "VND": 4615.7074,
    "VUV": 21.3158,
    "WST": 0.4711,
    "XAF": 100.9656,
    "XCD": 0.4859,
    "XCG": 0.3222,
    "XDR": 0.1321,
    "XOF": 100.9656,
    "XPF": 18.3677,
    "YER": 43.4017,
    "ZAR": 3.2231,
    "ZMW": 4.2108,
    "ZWL": 4.8304
  }
}
